My best work has been done
Victoria-Fire/MyTestRepository pull request #9
Opened 2021-02-02 12:52 UTC by Victoria-Fire

2021-02-02 13:02 UTC, Superman-777 requested changes
See notes

2021-02-02 13:02 UTC, Superman-777 commented on Hero/Super_Hero/Batman.md
> +```
What do you want?

1. What
2. do
3. you
4. want

- 1
- 2
- 3

- [ ] ok

2021-02-03 08:02 UTC, Victoria-Fire commented on Hero/Super_Hero/Batman.md
> +```
Good

2021-02-03 08:10 UTC, Superman-777 requested changes
See notes

2021-02-03 08:10 UTC, Superman-777 commented on Hero/Super_Hero/Batman.md
> +```
Deleted it

2021-02-03 08:12 UTC, Superman-777 approved these changes
Lgfm

2021-02-03 08:14 UTC, Superman-777 requested changes
see notes

2021-02-03 08:14 UTC, Superman-777 commented on Hero/Super_Hero/Batman.md
> +This new cjde for my test repository
what new?

2021-02-03 08:16 UTC, Superman-777 approved these changes
Lgfm

2021-02-03 08:17 UTC, merged

2021-02-03 08:18 UTC, Victoria-Fire commented
Tester_2 deleted